import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../App';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';
import { Badge } from '../components/ui/badge';
import { Alert, AlertDescription } from '../components/ui/alert';
import { 
  ArrowLeft,
  Settings,
  User,
  Building,
  FileText,
  Shield,
  Clock,
  Save,
  Upload,
  Download,
  Database,
  Activity,
  Bell,
  Palette,
  Globe,
  Key,
  Archive
} from 'lucide-react';

const AdminPanel = () => {
  const navigate = useNavigate();
  const { user, logout } = useAuth();
  const [activeTab, setActiveTab] = useState('clinic');
  const [saveStatus, setSaveStatus] = useState('');

  // Mock clinic settings
  const [clinicSettings, setClinicSettings] = useState({
    name: user?.clinic || 'Ayush Wellness Center',
    address: '123 Wellness Street, Mumbai, Maharashtra 400001',
    phone: '+91 9876543210',
    email: user?.email || 'contact@ayushwellness.com',
    license: user?.license || 'AYUSH/2024/001',
    language: 'English',
    timezone: 'Asia/Kolkata',
    currency: 'INR'
  });

  // Mock chart preferences
  const [chartPreferences, setChartPreferences] = useState({
    defaultCalories: 2000,
    includeMicronutrients: true,
    showAyurvedicProperties: true,
    enableClimateAdaptation: true,
    defaultMealCount: 4,
    includeTimings: true,
    logoUpload: false,
    watermark: true,
    footerText: 'Generated by AyushAahar - Intelligent Ayurvedic Diet Assistant'
  });

  // Mock audit logs
  const auditLogs = [
    {
      id: 1,
      action: 'Diet Chart Generated',
      patient: 'Priya Sharma',
      timestamp: '2024-01-15 10:30:00',
      ip: '192.168.1.100',
      status: 'success'
    },
    {
      id: 2,
      action: 'Patient Profile Updated',
      patient: 'Rajesh Kumar',
      timestamp: '2024-01-15 09:45:00',
      ip: '192.168.1.100',
      status: 'success'
    },
    {
      id: 3,
      action: 'Settings Modified',
      patient: 'System',
      timestamp: '2024-01-14 16:20:00',
      ip: '192.168.1.100',
      status: 'success'
    },
    {
      id: 4,
      action: 'Login Attempt',
      patient: 'Demo User',
      timestamp: '2024-01-14 14:15:00',
      ip: '203.0.113.1',
      status: 'success'
    },
    {
      id: 5,
      action: 'Password Change',
      patient: 'System',
      timestamp: '2024-01-13 11:30:00',
      ip: '192.168.1.100',
      status: 'success'
    }
  ];

  // Mock diet templates
  const dietTemplates = [
    {
      id: 1,
      name: 'Summer Cooling Diet',
      description: 'Pitta-pacifying foods for hot weather',
      usageCount: 45,
      lastUsed: '2024-01-15',
      status: 'active'
    },
    {
      id: 2,
      name: 'Winter Warming Protocol',
      description: 'Vata-balancing foods for cold season',
      usageCount: 32,
      lastUsed: '2024-01-12',
      status: 'active'
    },
    {
      id: 3,
      name: 'Diabetic Management',
      description: 'Low glycemic Ayurvedic approach',
      usageCount: 28,
      lastUsed: '2024-01-14',
      status: 'active'
    },
    {
      id: 4,
      name: 'Weight Loss Protocol',
      description: 'Kapha-reducing diet plan',
      usageCount: 38,
      lastUsed: '2024-01-13',
      status: 'inactive'
    }
  ];

  const handleClinicSettingChange = (field, value) => {
    setClinicSettings(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleChartPreferenceChange = (field, value) => {
    setChartPreferences(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const saveSettings = () => {
    setSaveStatus('saving');
    // Simulate API call
    setTimeout(() => {
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus(''), 3000);
    }, 1000);
  };

  const exportData = () => {
    alert('Data export functionality would be implemented here');
  };

  const importData = () => {
    alert('Data import functionality would be implemented here');
  };

  const getStatusBadge = (status) => {
    return status === 'active' 
      ? <Badge className="bg-green-100 text-green-800">Active</Badge>
      : <Badge variant="outline" className="text-slate-600">Inactive</Badge>;
  };

  const tabs = [
    { id: 'clinic', label: 'Clinic Settings', icon: Building },
    { id: 'charts', label: 'Chart Preferences', icon: FileText },
    { id: 'templates', label: 'Diet Templates', icon: Archive },
    { id: 'security', label: 'Security', icon: Shield },
    { id: 'audit', label: 'Audit Logs', icon: Activity }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-green-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-slate-200">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button 
                variant="ghost" 
                onClick={() => navigate('/dashboard')}
                className="text-slate-600 hover:text-slate-800"
              >
                <ArrowLeft className="h-4 w-4 mr-2" />
                Dashboard
              </Button>
              <div>
                <h1 className="text-2xl font-bold text-slate-800">Admin Panel</h1>
                <p className="text-slate-600">Manage your clinic settings and preferences</p>
              </div>
            </div>
            <div className="flex space-x-3">
              {saveStatus && (
                <Alert className={`${saveStatus === 'saved' ? 'border-green-200 bg-green-50' : 'border-blue-200 bg-blue-50'} px-4 py-2`}>
                  <AlertDescription className={`${saveStatus === 'saved' ? 'text-green-700' : 'text-blue-700'} text-sm`}>
                    {saveStatus === 'saving' ? 'Saving...' : 'Settings saved successfully!'}
                  </AlertDescription>
                </Alert>
              )}
              <Button 
                onClick={saveSettings}
                disabled={saveStatus === 'saving'}
                className="bg-gradient-to-r from-emerald-600 to-blue-600 hover:from-emerald-700 hover:to-blue-700"
              >
                <Save className="h-4 w-4 mr-2" />
                Save Changes
              </Button>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto p-6">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          {/* Sidebar Navigation */}
          <Card className="shadow-lg h-fit">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Settings className="h-5 w-5" />
                Settings Menu
              </CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <nav className="space-y-1">
                {tabs.map((tab) => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`w-full flex items-center gap-3 px-4 py-3 text-left transition-colors ${
                      activeTab === tab.id
                        ? 'bg-blue-50 text-blue-700 border-r-2 border-blue-600'
                        : 'text-slate-600 hover:bg-slate-50'
                    }`}
                  >
                    <tab.icon className="h-4 w-4" />
                    {tab.label}
                  </button>
                ))}
              </nav>
            </CardContent>
          </Card>

          {/* Main Content */}
          <div className="lg:col-span-3 space-y-6">
            {/* Clinic Settings */}
            {activeTab === 'clinic' && (
              <Card className="shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Building className="h-5 w-5" />
                    Clinic Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="clinicName">Clinic Name</Label>
                      <Input
                        id="clinicName"
                        value={clinicSettings.name}
                        onChange={(e) => handleClinicSettingChange('name', e.target.value)}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="phone">Phone Number</Label>
                      <Input
                        id="phone"
                        value={clinicSettings.phone}
                        onChange={(e) => handleClinicSettingChange('phone', e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="address">Address</Label>
                    <Input
                      id="address"
                      value={clinicSettings.address}
                      onChange={(e) => handleClinicSettingChange('address', e.target.value)}
                    />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="email">Email</Label>
                      <Input
                        id="email"
                        type="email"
                        value={clinicSettings.email}
                        onChange={(e) => handleClinicSettingChange('email', e.target.value)}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="license">AYUSH License</Label>
                      <Input
                        id="license"
                        value={clinicSettings.license}
                        onChange={(e) => handleClinicSettingChange('license', e.target.value)}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="space-y-2">
                      <Label>Language</Label>
                      <Select value={clinicSettings.language} onValueChange={(value) => handleClinicSettingChange('language', value)}>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="English">English</SelectItem>
                          <SelectItem value="Hindi">Hindi</SelectItem>
                          <SelectItem value="Marathi">Marathi</SelectItem>
                          <SelectItem value="Tamil">Tamil</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-2">
                      <Label>Timezone</Label>
                      <Select value={clinicSettings.timezone} onValueChange={(value) => handleClinicSettingChange('timezone', value)}>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Asia/Kolkata">Asia/Kolkata</SelectItem>
                          <SelectItem value="Asia/Mumbai">Asia/Mumbai</SelectItem>
                          <SelectItem value="Asia/Delhi">Asia/Delhi</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-2">
                      <Label>Currency</Label>
                      <Select value={clinicSettings.currency} onValueChange={(value) => handleClinicSettingChange('currency', value)}>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="INR">INR (₹)</SelectItem>
                          <SelectItem value="USD">USD ($)</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Chart Preferences */}
            {activeTab === 'charts' && (
              <Card className="shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileText className="h-5 w-5" />
                    Diet Chart Preferences
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-4">
                      <div className="space-y-2">
                        <Label htmlFor="defaultCalories">Default Calorie Target</Label>
                        <Input
                          id="defaultCalories"
                          type="number"
                          value={chartPreferences.defaultCalories}
                          onChange={(e) => handleChartPreferenceChange('defaultCalories', parseInt(e.target.value))}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="defaultMealCount">Default Meal Count</Label>
                        <Select 
                          value={chartPreferences.defaultMealCount.toString()} 
                          onValueChange={(value) => handleChartPreferenceChange('defaultMealCount', parseInt(value))}
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="3">3 Meals</SelectItem>
                            <SelectItem value="4">4 Meals</SelectItem>
                            <SelectItem value="5">5 Meals</SelectItem>
                            <SelectItem value="6">6 Meals</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <Label>Include Micronutrients</Label>
                        <input 
                          type="checkbox" 
                          checked={chartPreferences.includeMicronutrients}
                          onChange={(e) => handleChartPreferenceChange('includeMicronutrients', e.target.checked)}
                          className="toggle"
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label>Show Ayurvedic Properties</Label>
                        <input 
                          type="checkbox" 
                          checked={chartPreferences.showAyurvedicProperties}
                          onChange={(e) => handleChartPreferenceChange('showAyurvedicProperties', e.target.checked)}
                          className="toggle"
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label>Enable Climate Adaptation</Label>
                        <input 
                          type="checkbox" 
                          checked={chartPreferences.enableClimateAdaptation}
                          onChange={(e) => handleChartPreferenceChange('enableClimateAdaptation', e.target.checked)}
                          className="toggle"
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label>Include Meal Timings</Label>
                        <input 
                          type="checkbox" 
                          checked={chartPreferences.includeTimings}
                          onChange={(e) => handleChartPreferenceChange('includeTimings', e.target.checked)}
                          className="toggle"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="footerText">Chart Footer Text</Label>
                      <Input
                        id="footerText"
                        value={chartPreferences.footerText}
                        onChange={(e) => handleChartPreferenceChange('footerText', e.target.value)}
                      />
                    </div>
                    
                    <div className="flex items-center justify-between p-4 bg-slate-50 rounded-lg">
                      <div>
                        <Label>Clinic Logo Upload</Label>
                        <p className="text-sm text-slate-600">Add your clinic logo to diet charts</p>
                      </div>
                      <Button variant="outline">
                        <Upload className="h-4 w-4 mr-2" />
                        Upload Logo
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Diet Templates */}
            {activeTab === 'templates' && (
              <Card className="shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Archive className="h-5 w-5" />
                    Diet Templates Management
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {dietTemplates.map((template) => (
                      <div key={template.id} className="flex items-center justify-between p-4 border border-slate-200 rounded-lg">
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-2">
                            <h3 className="font-medium text-slate-800">{template.name}</h3>
                            {getStatusBadge(template.status)}
                          </div>
                          <p className="text-sm text-slate-600 mb-2">{template.description}</p>
                          <div className="flex items-center gap-4 text-xs text-slate-500">
                            <span>Used {template.usageCount} times</span>
                            <span>Last used: {new Date(template.lastUsed).toLocaleDateString('en-IN')}</span>
                          </div>
                        </div>
                        <div className="flex space-x-2">
                          <Button variant="outline" size="sm">Edit</Button>
                          <Button variant="outline" size="sm">Clone</Button>
                          <Button variant="outline" size="sm" className="text-red-600 hover:text-red-700">
                            Delete
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                  
                  <div className="mt-6">
                    <Button className="bg-gradient-to-r from-emerald-600 to-blue-600 hover:from-emerald-700 hover:to-blue-700">
                      Create New Template
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Security */}
            {activeTab === 'security' && (
              <Card className="shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Shield className="h-5 w-5" />
                    Security Settings
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div className="space-y-4">
                    <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                      <div className="flex items-center gap-2 mb-2">
                        <Key className="h-4 w-4 text-yellow-600" />
                        <span className="font-medium text-yellow-800">Password Security</span>
                      </div>
                      <p className="text-sm text-yellow-700 mb-3">
                        Your password was last changed 30 days ago. Consider updating it for better security.
                      </p>
                      <Button size="sm" variant="outline" className="border-yellow-300 text-yellow-700">
                        Change Password
                      </Button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="p-4 border border-slate-200 rounded-lg">
                        <h3 className="font-medium text-slate-800 mb-2">Session Management</h3>
                        <p className="text-sm text-slate-600 mb-3">
                          Current session: Active since login
                        </p>
                        <Button size="sm" variant="outline">
                          View All Sessions
                        </Button>
                      </div>

                      <div className="p-4 border border-slate-200 rounded-lg">
                        <h3 className="font-medium text-slate-800 mb-2">Two-Factor Authentication</h3>
                        <p className="text-sm text-slate-600 mb-3">
                          Enhance security with 2FA
                        </p>
                        <Button size="sm" variant="outline">
                          Enable 2FA
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Audit Logs */}
            {activeTab === 'audit' && (
              <Card className="shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Activity className="h-5 w-5" />
                    Audit Logs
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {auditLogs.map((log) => (
                      <div key={log.id} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg">
                        <div className="flex-1">
                          <div className="flex items-center gap-3 mb-1">
                            <span className="font-medium text-slate-800">{log.action}</span>
                            <Badge variant="outline" className="text-green-600 border-green-300">
                              {log.status}
                            </Badge>
                          </div>
                          <div className="flex items-center gap-4 text-sm text-slate-600">
                            <span>User: {log.patient}</span>
                            <span>IP: {log.ip}</span>
                          </div>
                        </div>
                        <div className="text-right">
                          <div className="text-sm text-slate-800">{log.timestamp.split(' ')[1]}</div>
                          <div className="text-xs text-slate-500">{log.timestamp.split(' ')[0]}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                  
                  <div className="mt-6 flex justify-between">
                    <Button variant="outline">
                      <Download className="h-4 w-4 mr-2" />
                      Export Logs
                    </Button>
                    <div className="text-sm text-slate-600">
                      Showing last 5 activities • Total: 156 entries
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Data Management */}
            <Card className="shadow-lg border-blue-200">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Database className="h-5 w-5" />
                  Data Management
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 border border-slate-200 rounded-lg">
                    <h3 className="font-medium text-slate-800 mb-2">Backup & Restore</h3>
                    <p className="text-sm text-slate-600 mb-3">
                      Last backup: January 15, 2024
                    </p>
                    <div className="flex space-x-2">
                      <Button size="sm" variant="outline" onClick={exportData}>
                        <Download className="h-3 w-3 mr-1" />
                        Export
                      </Button>
                      <Button size="sm" variant="outline" onClick={importData}>
                        <Upload className="h-3 w-3 mr-1" />
                        Import
                      </Button>
                    </div>
                  </div>

                  <div className="p-4 border border-red-200 rounded-lg bg-red-50">
                    <h3 className="font-medium text-red-800 mb-2">Danger Zone</h3>
                    <p className="text-sm text-red-600 mb-3">
                      Permanently delete all data
                    </p>
                    <Button size="sm" variant="destructive">
                      Delete All Data
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminPanel;